import React, { useState } from 'react';
import { 
  Sparkles, 
  Copy, 
  Check, 
  Download, 
  RefreshCw, 
  Sliders, 
  CheckCircle2, 
  ListChecks, 
  Lightbulb, 
  MessageSquare, 
  FileText, 
  ArrowRight,
  TrendingDown,
  Clock,
  Layers
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { SummarizeRequest, SummarizeResponse, SampleDocument } from '../types';
import { FileUploader } from './FileUploader';
import { StatsBar } from './StatsBar';

interface SummarizerViewProps {
  initialText?: string;
  onSendToChat?: (question: string, contextDoc: string) => void;
  samples: SampleDocument[];
}

export const SummarizerView: React.FC<SummarizerViewProps> = ({
  initialText = '',
  onSendToChat,
  samples,
}) => {
  const [inputText, setInputText] = useState(initialText);
  const [attachedFile, setAttachedFile] = useState<{ name: string; mimeType?: string; data?: string } | null>(null);
  const [format, setFormat] = useState<'executive' | 'bullets' | 'tldr' | 'action-items' | 'detailed'>('executive');
  const [length, setLength] = useState<'short' | 'medium' | 'detailed'>('medium');
  const [targetAudience, setTargetAudience] = useState<'general' | 'executives' | 'technical' | 'students'>('general');
  
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [summaryData, setSummaryData] = useState<SummarizeResponse | null>(null);
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  const handleSummarize = async () => {
    if (!inputText.trim() && !attachedFile?.data) {
      setError('Please enter some text or upload a document to summarize.');
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const payload: SummarizeRequest = {
        text: inputText,
        format,
        length,
        targetAudience,
        imagePart: attachedFile?.data && attachedFile.mimeType ? {
          mimeType: attachedFile.mimeType,
          data: attachedFile.data,
        } : undefined,
      };

      const res = await fetch('/api/OpenAi/summarize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const errData = await res.json().catch(() => ({ error: 'Failed to generate summary' }));
        throw new Error(errData.error || `Server responded with status ${res.status}`);
      }

      const data: SummarizeResponse = await res.json();
      setSummaryData(data);
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'An unexpected error occurred while communicating with OpenAi.');
    } finally {
      setIsLoading(false);
    }
  };

  const copyToClipboard = (text: string, sectionId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionId);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const handleDownloadMarkdown = () => {
    if (!summaryData) return;
    const mdContent = `# Document Summary & Intelligence Report

## TL;DR
${summaryData.tldr}

## Executive Summary
${summaryData.executiveSummary}

## Key Takeaways
${summaryData.keyPoints.map(p => `- ${p}`).join('\n')}

## Extracted Action Items
${summaryData.actionItems.map(a => `- [ ] ${a}`).join('\n')}

---
*Generated by AI Smart Assistant (OpenAi 3.7 Flash) | ${new Date().toLocaleDateString()}*
`;
    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `summary-report-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div id="summarizer-view" className="space-y-6">
      {/* Top Header & Actions */}
      <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Text Summarization</h2>
          <p className="text-slate-500 dark:text-slate-400 text-sm mt-0.5">Upload or paste text for intelligent summarization and suggestions.</p>
        </div>
        <div className="flex items-center gap-2">
          {inputText && (
            <button
              onClick={() => {
                setInputText('');
                setAttachedFile(null);
                setSummaryData(null);
              }}
              className="px-4 py-2 border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 rounded-lg text-sm font-medium text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800 transition cursor-pointer"
            >
              Clear
            </button>
          )}
          <button
            id="btn-process-text"
            onClick={handleSummarize}
            disabled={isLoading || (!inputText.trim() && !attachedFile?.data)}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-300 dark:disabled:bg-slate-800 text-white rounded-lg text-sm font-medium shadow-xs shadow-indigo-200 dark:shadow-none transition cursor-pointer flex items-center gap-1.5 disabled:cursor-not-allowed"
          >
            {isLoading ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin text-white" />
                <span>Processing...</span>
              </>
            ) : (
              <span>Process Text</span>
            )}
          </button>
        </div>
      </header>

      {/* Quick Test Presets Pill Bar */}
      <div className="flex flex-wrap items-center gap-2 pb-1">
        <span className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest">Quick Presets:</span>
        {samples.map((sample) => (
          <button
            key={sample.id}
            onClick={() => {
              setInputText(sample.text);
              setAttachedFile(null);
              setSummaryData(null);
            }}
            className="text-xs px-2.5 py-1 rounded-lg bg-white dark:bg-slate-900 hover:bg-indigo-50 dark:hover:bg-indigo-950/50 hover:text-indigo-600 dark:hover:text-indigo-300 text-slate-600 dark:text-slate-300 font-medium border border-slate-200 dark:border-slate-800 transition cursor-pointer"
          >
            {sample.title}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Input and Configuration Panel */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5 shadow-xs flex flex-col space-y-3 transition-colors">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100 dark:border-slate-800">
              <span className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest">
                Source Input
              </span>
              <span className="text-[10px] text-slate-400 dark:text-slate-500 font-medium">
                {inputText.trim() ? `${inputText.trim().split(/\s+/).length} Words` : 'Empty'}
              </span>
            </div>

            {/* Document Uploader */}
            <FileUploader
              onFileLoaded={(content, fileName, imgPart) => {
                if (content) setInputText(content);
                setAttachedFile({ name: fileName, ...imgPart });
              }}
              onClearFile={() => setAttachedFile(null)}
              attachedFileName={attachedFile?.name}
            />

            {/* Input Textarea */}
            <div className="relative">
              <textarea
                id="summarizer-input"
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                placeholder="Paste articles, meeting notes, project briefs, or reports here..."
                rows={9}
                className="w-full text-xs text-slate-800 dark:text-slate-100 bg-slate-50/50 dark:bg-slate-800/60 p-3 rounded-lg border border-slate-200 dark:border-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition font-mono leading-relaxed resize-y"
              />
            </div>

            <StatsBar text={inputText} />

            {/* Controls Section */}
            <div className="pt-3 border-t border-slate-100 dark:border-slate-800 space-y-3">
              <span className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest block">
                Parameters & Audience
              </span>

              {/* Format Select */}
              <div className="grid grid-cols-2 gap-2 text-xs">
                <div>
                  <label htmlFor="format-select" className="block text-[11px] font-medium text-slate-500 dark:text-slate-400 mb-1">
                    Output Format
                  </label>
                  <select
                    id="format-select"
                    value={format}
                    onChange={(e: any) => setFormat(e.target.value)}
                    className="w-full bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-700 dark:text-slate-200 focus:outline-none focus:border-indigo-500 cursor-pointer"
                  >
                    <option value="executive">Executive Memo</option>
                    <option value="bullets">Bulleted Takeaways</option>
                    <option value="tldr">Quick TL;DR</option>
                    <option value="action-items">Action Plan Focus</option>
                    <option value="detailed">In-Depth Analysis</option>
                  </select>
                </div>

                <div>
                  <label htmlFor="length-select" className="block text-[11px] font-medium text-slate-500 dark:text-slate-400 mb-1">
                    Summary Length
                  </label>
                  <select
                    id="length-select"
                    value={length}
                    onChange={(e: any) => setLength(e.target.value)}
                    className="w-full bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-700 dark:text-slate-200 focus:outline-none focus:border-indigo-500 cursor-pointer"
                  >
                    <option value="short">Concise (~150 words)</option>
                    <option value="medium">Standard (~300 words)</option>
                    <option value="detailed">Comprehensive (~500 words)</option>
                  </select>
                </div>
              </div>

              {/* Target Audience */}
              <div>
                <label htmlFor="audience-select" className="block text-[11px] font-medium text-slate-500 dark:text-slate-400 mb-1">
                  Target Audience
                </label>
                <select
                  id="audience-select"
                  value={targetAudience}
                  onChange={(e: any) => setTargetAudience(e.target.value)}
                  className="w-full bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-700 dark:text-slate-200 focus:outline-none focus:border-indigo-500 cursor-pointer"
                >
                  <option value="general">General Professional Audience</option>
                  <option value="executives">C-Suite & Leadership (ROI & Strategy)</option>
                  <option value="technical">Engineering & Technical Teams</option>
                  <option value="students">Educational / Simplified</option>
                </select>
              </div>
            </div>

            {/* Error Message */}
            {error && (
              <div className="p-3 rounded-lg bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-800 text-xs text-red-700 dark:text-red-300 flex items-start space-x-2">
                <span className="font-semibold">Error:</span>
                <span>{error}</span>
              </div>
            )}
          </div>
        </div>

        {/* Right Column: Output Intelligence Dashboard */}
        <div className="lg:col-span-7 space-y-4">
          {!summaryData && !isLoading && (
            <div className="bg-white dark:bg-slate-900 rounded-xl p-10 border border-slate-200 dark:border-slate-800 shadow-xs text-center flex flex-col items-center justify-center min-h-[380px] transition-colors">
              <div className="w-12 h-12 rounded-xl bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400 flex items-center justify-center mb-3">
                <FileText className="w-6 h-6" />
              </div>
              <h3 className="text-sm font-semibold text-slate-800 dark:text-white">Ready for Document Analysis</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400 max-w-sm mt-1">
                Paste source text or select a preset, then click Process Text to generate structured executive summaries and suggestions.
              </p>
              <button
                onClick={() => {
                  if (samples[0]) {
                    setInputText(samples[0].text);
                    setAttachedFile(null);
                  }
                }}
                className="mt-4 px-4 py-2 rounded-lg bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 text-indigo-600 dark:text-indigo-300 text-xs font-medium border border-slate-200 dark:border-slate-700 transition cursor-pointer"
              >
                Load Sample Memo & Test
              </button>
            </div>
          )}

          {isLoading && (
            <div className="bg-white dark:bg-slate-900 rounded-xl p-8 border border-slate-200 dark:border-slate-800 shadow-xs space-y-4 min-h-[380px] flex flex-col justify-center transition-colors">
              <div className="flex items-center space-x-3 text-indigo-600 dark:text-indigo-400">
                <RefreshCw className="w-4 h-4 animate-spin" />
                <span className="text-xs font-semibold tracking-wide uppercase">Synthesizing with OpenAi...</span>
              </div>
              <div className="space-y-2.5 animate-pulse">
                <div className="h-4 bg-slate-100 dark:bg-slate-800 rounded w-3/4"></div>
                <div className="h-4 bg-slate-100 dark:bg-slate-800 rounded w-full"></div>
                <div className="h-4 bg-slate-100 dark:bg-slate-800 rounded w-5/6"></div>
                <div className="h-20 bg-slate-50 dark:bg-slate-800/50 rounded-lg w-full mt-4"></div>
                <div className="h-4 bg-slate-100 dark:bg-slate-800 rounded w-1/2 mt-4"></div>
              </div>
            </div>
          )}

          {summaryData && !isLoading && (
            <div className="space-y-4 animate-in fade-in duration-200">
              {/* Executive Summary Card in Deep Indigo */}
              <div className="bg-indigo-900 dark:bg-indigo-950/80 rounded-xl p-5 text-white shadow-xl relative overflow-hidden border dark:border-indigo-900/50">
                <div className="relative z-10">
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-[10px] font-bold text-indigo-300 uppercase tracking-widest">
                      AI Executive Summary
                    </span>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => copyToClipboard(summaryData.executiveSummary, 'exec')}
                        className="text-indigo-200 hover:text-white text-xs flex items-center gap-1 transition cursor-pointer"
                      >
                        {copiedSection === 'exec' ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                        <span>{copiedSection === 'exec' ? 'Copied' : 'Copy'}</span>
                      </button>
                      <button
                        onClick={handleDownloadMarkdown}
                        className="text-indigo-200 hover:text-white text-xs flex items-center gap-1 transition cursor-pointer"
                        title="Download Markdown Report"
                      >
                        <Download className="w-3 h-3" />
                        <span>Export</span>
                      </button>
                    </div>
                  </div>

                  <h3 className="text-base font-semibold mb-2 text-white">
                    {summaryData.tldr}
                  </h3>

                  <div className="text-xs text-indigo-100 leading-relaxed prose-sm max-w-none pt-1">
                    <ReactMarkdown>{summaryData.executiveSummary}</ReactMarkdown>
                  </div>
                </div>
                <div className="absolute top-[-20%] right-[-10%] w-48 h-48 bg-indigo-500 rounded-full blur-[80px] opacity-20 pointer-events-none"></div>
              </div>

              {/* Key Takeaways & Intelligent Suggestions Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Key Takeaways */}
                {summaryData.keyPoints && summaryData.keyPoints.length > 0 && (
                  <div className="bg-white dark:bg-slate-900 rounded-xl p-5 border border-slate-200 dark:border-slate-800 shadow-xs space-y-3 transition-colors">
                    <span className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest block">
                      Key Takeaways
                    </span>
                    <ul className="space-y-2 text-xs text-slate-700 dark:text-slate-300">
                      {summaryData.keyPoints.map((point, idx) => (
                        <li key={idx} className="flex gap-2">
                          <span className="text-indigo-600 dark:text-indigo-400 font-bold">•</span>
                          <span className="leading-relaxed">{point}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Intelligent Action Items / Suggestions */}
                <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5 shadow-xs space-y-3 transition-colors">
                  <span className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest block">
                    Intelligent Suggestions & Directives
                  </span>
                  <div className="space-y-2.5">
                    {summaryData.actionItems && summaryData.actionItems.length > 0 ? (
                      summaryData.actionItems.map((action, idx) => (
                        <div key={idx} className="p-3 border border-indigo-100 dark:border-indigo-900/50 bg-indigo-50/50 dark:bg-indigo-950/30 rounded-lg">
                          <p className="text-xs font-bold text-indigo-900 dark:text-indigo-300">Action Item {idx + 1}</p>
                          <p className="text-[11px] text-indigo-700 dark:text-indigo-400 mt-0.5 leading-relaxed">{action}</p>
                        </div>
                      ))
                    ) : (
                      <div className="p-3 border border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/40 rounded-lg">
                        <p className="text-xs font-bold text-slate-700 dark:text-slate-300">Analysis Complete</p>
                        <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5">All directives and key arguments successfully indexed.</p>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Stats Bar */}
              <div className="grid grid-cols-3 gap-3">
                <div className="bg-white dark:bg-slate-900 p-3 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs flex items-center space-x-2.5 transition-colors">
                  <div className="p-2 rounded-lg bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400">
                    <TrendingDown className="w-4 h-4" />
                  </div>
                  <div>
                    <div className="text-xs font-bold text-slate-800 dark:text-white">{summaryData.reductionPercentage}%</div>
                    <div className="text-[10px] text-slate-400 dark:text-slate-500">Content Reduced</div>
                  </div>
                </div>

                <div className="bg-white dark:bg-slate-900 p-3 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs flex items-center space-x-2.5 transition-colors">
                  <div className="p-2 rounded-lg bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400">
                    <Layers className="w-4 h-4" />
                  </div>
                  <div>
                    <div className="text-xs font-bold text-slate-800 dark:text-white">
                      {summaryData.wordCount} <span className="text-[10px] font-normal text-slate-400 dark:text-slate-500">/ {summaryData.originalWordCount}w</span>
                    </div>
                    <div className="text-[10px] text-slate-400 dark:text-slate-500">Summary Word Count</div>
                  </div>
                </div>

                <div className="bg-white dark:bg-slate-900 p-3 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs flex items-center space-x-2.5 transition-colors">
                  <div className="p-2 rounded-lg bg-purple-50 dark:bg-purple-950/60 text-purple-600 dark:text-purple-400">
                    <Clock className="w-4 h-4" />
                  </div>
                  <div>
                    <div className="text-xs font-bold text-slate-800 dark:text-white">~{summaryData.readingTimeMinutes} min</div>
                    <div className="text-[10px] text-slate-400 dark:text-slate-500">Reading Time</div>
                  </div>
                </div>
              </div>

              {/* Smart Follow-Up Questions (Direct Bridge to Chat) */}
              {summaryData.suggestedQuestions && summaryData.suggestedQuestions.length > 0 && (
                <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-4 shadow-xs space-y-2 transition-colors">
                  <div className="flex items-center justify-between text-xs text-slate-700 dark:text-slate-300 font-semibold">
                    <span className="flex items-center space-x-1.5">
                      <MessageSquare className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
                      <span>Explore Further in Question Answering</span>
                    </span>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {summaryData.suggestedQuestions.map((q, idx) => (
                      <button
                        key={idx}
                        onClick={() => onSendToChat && onSendToChat(q, inputText)}
                        className="text-xs px-3 py-1.5 rounded-lg bg-slate-50 dark:bg-slate-800 hover:bg-indigo-50 dark:hover:bg-indigo-950/50 text-slate-700 dark:text-slate-300 hover:text-indigo-700 dark:hover:text-indigo-300 border border-slate-200 dark:border-slate-700 transition flex items-center space-x-1.5 cursor-pointer text-left font-medium"
                      >
                        <span>{q}</span>
                        <ArrowRight className="w-3 h-3 text-indigo-500 dark:text-indigo-400 shrink-0" />
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
